# -*- coding: utf-8 -*-
"""map-reduce

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LsFdN3006N1ZnrWa3uCeIT-BCzl56imu
"""

!pip install mrjob
from mrjob.job import MRJob
import csv

class MRTagsCount(MRJob):

    # Fonction Mapper
    def mapper(self, _, line):
        # Ignorer la ligne d'en-tête
        if line.startswith("moveId"):
            return
        # Charger chaque ligne CSV
        reader = csv.DictReader([line])  # Lire la ligne comme un dictionnaire
        for row in reader:
            move_id = row['moveId']
            # Émettre le couple clé-valeur (moveId, 1) pour chaque tag
            yield (move_id, 1)

    # Fonction Reducer
    def reducer(self, move_id, counts):
        # Calculer le total des tags par moveId
        yield (move_id, sum(counts))


if __name__ == '__main__':
    MRTagsCount.run()