# -*- coding: utf-8 -*-
"""map-reduce2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LsFdN3006N1ZnrWa3uCeIT-BCzl56imu
"""

from mrjob.job import MRJob
from mrjob.step import MRStep

class TagCounts(MRJob):
    def steps(self):
        return [
            MRStep(mapper=self.mapper_get_tags,
                   reducer=self.reducer_count_tags)
        ]

    def mapper_get_tags(self, _, line):
        try:
            userID, movieID, tag, timestamp = line.split(',')
            yield userID, 1  # Nous émettons l'userID et 1 pour chaque tag ajouté par cet utilisateur
        except Exception:
            pass

    def reducer_count_tags(self, userID, counts):
        yield userID, sum(counts)  # Nous additionnons tous les 1 pour obtenir le nombre de tags par utilisateur

if __name__ == '__main__':
    TagCounts.run()