# -*- coding: utf-8 -*-
"""map-reduce

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LsFdN3006N1ZnrWa3uCeIT-BCzl56imu
"""

from mrjob.job import MRJob
from mrjob.step import MRStep

class TagCounts(MRJob):
    def steps(self):
        return [
            MRStep(mapper=self.mapper_get_tags,
                   reducer=self.reducer_count_tags)
        ]

    def mapper_get_tags(self, _, line):
        try:
            userID, movieID, tag, timestamp = line.split(',')
            yield movieID, 1
        except Exception:
            pass

    def reducer_count_tags(self, movieID, counts):
        yield movieID, sum(counts)

if __name__ == '__main__':
    TagCounts.run()