# -*- coding: utf-8 -*-
"""map_reduce4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14v4LOb5awFzkpoIOBZTkxeVRq-e9QyxW
"""

from __future__ import print_function
from mrjob.job import MRJob
from mrjob.step import MRStep

class TagsPerUserPerFilm(MRJob):

    def steps(self):
        return [MRStep(mapper=self.mapper_get_user_film_tags, reducer=self.reducer_count_tags)]

    def mapper_get_user_film_tags(self, _, line):
        try:
            userID, movieId, tag, timestamp = line.strip().split(',')
            key = "{}_{}".format(userID, movieId)  # Compatible with Python 2
            yield key, tag
        except ValueError:
            pass  # Ignore bad lines

    def reducer_count_tags(self, user_film, tags):
        # Compter tous les tags (non uniques)
        yield user_film, sum(1 for _ in tags)

if __name__ == '__main__':
    TagsPerUserPerFilm.run()